defaults:
  - /tracking/base@_here_

buffer: 512
warmup: 12

motion_filter:
  thresh: 3.0

frontend:
  steps1: 4
  steps2: 2
  iters: 4

  max_age: 25

  keyframe_thresh: 3.0
  thresh: 18.0
  window: 30
  max_factors: 160
  radius: 5
  nms: 1

  release_cache: True
  pose_interpolation: linear

backend:
  warmup: 20
  do_refinement: True

  window: 150
  thresh: 55.0
  max_factor_mult: 8
  radius: 2
  nms: 2

  use_loop_closure: False
  loop_window: 40
  loop_thresh: 50.0
  loop_radius: 5
  loop_nms: 12
  loop_max_factor_mult: 16
